name: facturador
description: Sistema de facturación BN24
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  pdf: ^3.10.8
  printing: ^5.12.0
  fl_chart: ^0.68.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/IMG-20260228-WA0018.jpg

flutter_launcher_icons:
  android: true
  ios: false
  web:
    generate: true
    image_path: "assets/logo.jpg"
  windows:
    generate: true
    image_path: "assets/logo.jpg"
  image_path: "assets/logo.jpg"
